version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: next-config-sample
    environment:
      - DEBUG=${DEBUG}
    ports:
      - '3000:3000'
